---

- name: Copy ./dist
  become: true
  copy:
    src: dist
    dest: ~/app

- name: Install dependencies
  become: true
  shell: |
    cd ~/app
    npm i

- name: Start backend
  become: true
  command: pm2 start ~/app/main.js --name backend