---

- name: Creates App directory
  file:
    path: ~/app
    state: directory

- name: Upload dist to app directory
  become: true
  copy:
    src: "files/dist"
    dest: "~/app"

- name: Install dependencies
  become: true
  shell: |
    cd ~/app
    npm i

- name: Start backend
  become: true
  command: pm2 start ~/app/main.js --name backend -f