---

- name: Copy ./dist
  become: true
  copy:
    src: dist
    dest: /home/ubuntu

- name: Install dependencies
  become: true
  shell: |
    cd ~/dist
    npm i

- name: Start backend
  become: true
  command: pm2 start ~/dist/main.js --name backend