---

- name: Creates App directory
  file:
    path: ~/app
    state: directory

- name: Upload dist to app directory
  copy:
    src: files/dist.zip
    dest: "~/app"

- name: Install dependencies
  shell: |
    cd ~/app
    unzip dist.zip
    rm -rf dist.zip
    npm i

- name: Start backend
  command: pm2 start ~/app/main.js --name backend -f